apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tcpingressmap-editor-role
rules:
- apiGroups:
  - networking.infra.doodle.com
  resources:
  - tcpingressmappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.infra.doodle.com
  resources:
  - tcpingressmappings/status
  verbs:
  - get
